Matrice = [ ' ***   GW COMPUTATION   ***   2%    ',
            '           X XX X             4%    ',
            '          XXXXXXXX            6%    ',
            '          X X  X X            8%    ',
            '         X        X           10%   ',
            '         X        X           12%   ',
            '          XXXX XXX            14%   ',
            '         X    X  XX           16%   ',
            '        X          X          18%   ',
            '      XX            X         20%   ',
            ' X   X              XX        22%   ',
            '  XXX                 X       24%   ',
            ' X                    X       26%   ',
            '  X                  X        28%   ',
            ' X         XX     XX  X       30%   ',
            '  X       X  X   X X  X       32%   ',
            '   X      X   XXX XX X        34%   ',
            '    XX XX X  X   X XX         36%   ',
            '    X X X X  X   X XX         38%   ',
            '   X  X X  X X   X XXX        40%   ',
            'XXXX   X X X       X X        42%   ',
            ' X    X   X   XX  X X         44%   ',
            ' X     X X X     XX           46%   ',
            '  XX  XXXXX XXXXX  X          48%   ',
            ' X   X     X     X  XX        50%   ',
            '  X X       X     X  X        52%   ',
            '  X X       X     X  X        54%   ',
            '  X X      X      X  X        56%   ',
            '  X  X    XX      X X         58%   ',
            '   X  XXXX  X    X  X         60%   ',
            '   XX    X   X   X  X         62%   ',
            'XXXX    XX    X  X X          64%   ',
            ' X     X  X    XX  X          66%   ',
            '  X   X    X     X X          68%   ',
            '   X X      X     X X         70%   ',
            '    X        X     X X        72%   ',
            '              X   X  X        74%   ',
            '   X  X        XXX    X       76%   ',
            '  X  X    X       X   X       78%   ',
            ' X   X   X         X   X      80%   ',
            ' X   X   X         X   X      82%   ',
            ' X  X   X           X  X      84%   ',
            'X   X   X           X  X      86%   ',
            'X   X   X           X   X     88%   ',
            'X   X   X           X   X     90%   ',
            ' X  X   X           X   X     92%   ',
            '  XXX   X           X XX      94%   ',
            '     XXXXXX        XXX        96%   ',
            '           XXXXXXXX           98%   ',
            '   ***   GW COMPUTED   ***    100%  ' ]

def bar(n,ntot) :
    if (int(n) % int(ntot//50))==0 :
        print(Matrice[int(n)//int(ntot/50)] + str(n)+ '/'+str(ntot))