Matrice = [ ' ***   GW COMPUTATION   ***         ',
            '           X XX X             2%    ',
            '          XXXXXXXX            4%    ',
            '          X X  X X            6%    ',
            '         X        X           8%    ',
            '         X        X           10%   ',
            '          XXXX XXX            12%   ',
            '         X    X  XX           14%   ',
            '        X          X          16%   ',
            '      XX            X         18%   ',
            ' X   X              XX        20%   ',
            '  XXX                 X       22%   ',
            ' X                    X       24%   ',
            '  X                  X        26%   ',
            ' X         XX     XX  X       28%   ',
            '  X       X  X   X X  X       30%   ',
            '   X      X   XXX XX X        32%   ',
            '    XX XX X  X   X XX         34%   ',
            '    X X X X  X   X XX         36%   ',
            '   X  X X  X X   X XXX        38%   ',
            'XXXX   X X X       X X        40%   ',
            ' X    X   X   XX  X X         42%   ',
            ' X     X X X     XX           44%   ',
            '  XX  XXXXX XXXXX  X          46%   ',
            ' X   X     X     X  XX        48%   ',
            '  X X       X     X  X        50%   ',
            '  X X       X     X  X        52%   ',
            '  X X      X      X  X        54%   ',
            '  X  X    XX      X X         56%   ',
            '   X  XXXX  X    X  X         58%   ',
            '   XX    X   X   X  X         60%   ',
            'XXXX    XX    X  X X          62%   ',
            ' X     X  X    XX  X          64%   ',
            '  X   X    X     X X          66%   ',
            '   X X      X     X X         68%   ',
            '    X        X     X X        70%   ',
            '              X   X  X        72%   ',
            '   X  X        XXX    X       74%   ',
            '  X  X    X       X   X       76%   ',
            ' X   X   X         X   X      78%   ',
            ' X   X   X         X   X      80%   ',
            ' X  X   X           X  X      82%   ',
            'X   X   X           X  X      84%   ',
            'X   X   X           X   X     86%   ',
            'X   X   X           X   X     88%   ',
            ' X  X   X           X   X     90%   ',
            '  XXX   X           X XX      92%   ',
            '     XXXXXX        XXX        94%   ',
            '           XXXXXXXX           96%   ',
            '                              98%   ',
            '   ***   GW COMPUTED   ***    100%  ',    ]

def bar(n,ntot) :
    if (int(n) % int(ntot//50))==0 :
        print(Matrice[int(n)//int(ntot/50)] + str(n)+ '/'+str(ntot))